# Generated by Django 3.2.2 on 2021-05-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registermodels',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
