# Generated by Django 3.2.2 on 2021-05-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_registermodels_registermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
