# Generated by Django 3.2.2 on 2021-05-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_registermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
