# Generated by Django 3.2.2 on 2021-05-11 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.client', verbose_name='To Client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='app.organization', verbose_name='From Organization'),
        ),
        migrations.AddField(
            model_name='expenseclaimline',
            name='expense_claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='app.expenseclaim'),
        ),
        migrations.AddField(
            model_name='expenseclaimline',
            name='tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.taxrate'),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.employee', verbose_name='Paid by employee'),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_claims', to='app.organization', verbose_name='From Organization'),
        ),
        migrations.AddField(
            model_name='estimateline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='app.estimate'),
        ),
        migrations.AddField(
            model_name='estimateline',
            name='tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.taxrate'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.client', verbose_name='To Client'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='app.organization', verbose_name='From Organization'),
        ),
        migrations.AddField(
            model_name='billline',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='app.bill'),
        ),
        migrations.AddField(
            model_name='billline',
            name='tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.taxrate'),
        ),
        migrations.AddField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.client', verbose_name='From Client'),
        ),
        migrations.AddField(
            model_name='bill',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='app.organization', verbose_name='To Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('number', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='expenseclaim',
            unique_together={('number', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='estimate',
            unique_together={('number', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('number', 'organization')},
        ),
    ]
