# Generated by Django 3.2.2 on 2021-05-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(),
        ),
    ]
