# Generated by Django 3.2.2 on 2021-05-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210511_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
